### ISSUE TITLE
Remove all triggers

### ISSUE THREAD

**Issue by cd-a** [leona/helix-gpt#21]
Is there a way to remove all triggers and just trigger it manually with C-x?

I know you can override them, but I tried passing empty string and it didn't work.

```toml
[language-server.gpt]
command = "bun"
args = ["run", "/Users/att/.local/bin/helix-gpt.js"]
triggerCharacters = ""
```
