### ISSUE TITLE
[BUG] Can't install helix-gpt

### ISSUE THREAD

**Issue by TSGoose** [leona/helix-gpt#83]
**helix-editor version**
helix 25.01.1 (e7ac2fcd)

**helix-gpt version**
0.34

**Describe the bug**
I'm trying to install helix-gpt, but it's not working for me. I'm probably doing something wrong, but searches have not yielded any results. Now helix-gpt just doesn't work without giving any errors. 
I tried adding variables via `export HANDLER...` but that didn't help, I got the key for copilot from the instructions.

I tried installing without bun and with it, now I settled on the second method.

```toml
[language-server.phpactor]
command = "phpactor"
args = ["language-server"]

[language-server.gpt]
command = "HANDLER=copilot COPILOT_API_KEY=... bun"
args = ["run", "/usr/bin/helix-gpt", "--logFile", "/home/goose/helix-gpt.log"]

[[language]]
name = "php"
scope = "source.php"
injection-regex = "php"
file-types = ["php", "inc", "php4", "php5", "phtml", "ctp"]
shebangs = ["php"]
roots = ["composer.json", "index.php"]
comment-token = "//"
language-servers = [ "phpactor", "gpt" ]
indent = { tab-width = 4, unit = "    " }

[[language]]
name = "rust"
language-servers = [ "rust-analyzer", "gpt" ]
```

**helix-gpt logs**
Maybe I'm doing something wrong, but it's empty.

**helix logs**
Using the latest preset the helix logs are empty, but `lsp-restart` stops the base lsp working

**Comment by irdaislakhuafa** [comment]
hi, are you use binary of `helix-gpt` or `ts` code?
if you use non binary of `helix-gpt` try this config
```toml
[language-server.gpt]
command = "bun"
args = ["run", "/usr/bin/helix-gpt", "--handler", "copilot", "--copilotApiKey", "<your copilot api key here>" ]
```

if you use binary version of `helix-gpt` then try this one
```toml
[language-server.gpt]
command = "/usr/bin/helix-gpt"
args = ["--handler", "copilot", "--copilotApiKey", "<your copilot api key here>" ]
```

Please tell me if this config working or not for you.
